---
- name: Atualizando a lista de repositorios APT em WPNESELLO
  apt: update_cache=yes cache_valid_time=3600

- name: Instalando dependencias da aplicacao WP
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - php7.0-mysql
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-mcrypt
    - python-mysqldb

- name: Instalando extencoes PHP
  apt: name={{ item }} state=present
  with_items:
    - php7.0-gd 
    - php-ssh2

- name: Baixando o Wordpress 
  get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz validate_certs=no 

- name: Descompactando arquivo do Wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no

- name: Alterando diretorio de site padrao do Apache2
  lineinfile: dest=/etc/apache2/sites-enabled/000-default.conf regexp="(.)+DocumentRoot /var/www/html" line="DocumentRoot /var/www/html/wordpress"
  notify:
    - Reiniciando Servidor Apache2

- name: Copiando modelo de configuracao do Wordpress
  command: cp -frv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php

- name: Configurando o WordPress em wp-config.php
  lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="{{ item.regexp }}" line="{{ item.line }}"

  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ wp_mysql_db }}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ wp_mysql_user }}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ wp_mysql_password }}');"}

